/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSquareCallbackRouteImport } from './routes/api/square/callback'
import { Route as ApiPublicToastWebhookRouteImport } from './routes/api/public/toast/webhook'
import { Route as ApiPublicSquareWebhookRouteImport } from './routes/api/public/square/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSquareCallbackRoute = ApiSquareCallbackRouteImport.update({
  id: '/api/square/callback',
  path: '/api/square/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicToastWebhookRoute = ApiPublicToastWebhookRouteImport.update({
  id: '/api/public/toast/webhook',
  path: '/api/public/toast/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSquareWebhookRoute = ApiPublicSquareWebhookRouteImport.update({
  id: '/api/public/square/webhook',
  path: '/api/public/square/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/square/callback': typeof ApiSquareCallbackRoute
  '/api/public/square/webhook': typeof ApiPublicSquareWebhookRoute
  '/api/public/toast/webhook': typeof ApiPublicToastWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/square/callback': typeof ApiSquareCallbackRoute
  '/api/public/square/webhook': typeof ApiPublicSquareWebhookRoute
  '/api/public/toast/webhook': typeof ApiPublicToastWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/square/callback': typeof ApiSquareCallbackRoute
  '/api/public/square/webhook': typeof ApiPublicSquareWebhookRoute
  '/api/public/toast/webhook': typeof ApiPublicToastWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/square/callback'
    | '/api/public/square/webhook'
    | '/api/public/toast/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/square/callback'
    | '/api/public/square/webhook'
    | '/api/public/toast/webhook'
  id:
    | '__root__'
    | '/'
    | '/api/square/callback'
    | '/api/public/square/webhook'
    | '/api/public/toast/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSquareCallbackRoute: typeof ApiSquareCallbackRoute
  ApiPublicSquareWebhookRoute: typeof ApiPublicSquareWebhookRoute
  ApiPublicToastWebhookRoute: typeof ApiPublicToastWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/square/callback': {
      id: '/api/square/callback'
      path: '/api/square/callback'
      fullPath: '/api/square/callback'
      preLoaderRoute: typeof ApiSquareCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/toast/webhook': {
      id: '/api/public/toast/webhook'
      path: '/api/public/toast/webhook'
      fullPath: '/api/public/toast/webhook'
      preLoaderRoute: typeof ApiPublicToastWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/square/webhook': {
      id: '/api/public/square/webhook'
      path: '/api/public/square/webhook'
      fullPath: '/api/public/square/webhook'
      preLoaderRoute: typeof ApiPublicSquareWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSquareCallbackRoute: ApiSquareCallbackRoute,
  ApiPublicSquareWebhookRoute: ApiPublicSquareWebhookRoute,
  ApiPublicToastWebhookRoute: ApiPublicToastWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
